language: python
services: 
  - postgresql
before_script:
  - psql -c  'create database travic;' -U postgres 
jobs:
  include: 
    stage: preparation
    script:
      - pip install -r requirements.txt
      - cd mysite
      - python manage.py migrate
    stage: runserver
    script: python manage.py runserver
    stage: print
    script: echo "Hello, World!"