language: python
services: 
  - postgresql
before_script:
  - psql -c  'create database travic;' -U postgres 
script: 
  - pip install -r requirements.txt
  - cd mysite
  - python manage.py migrate
  - python manage.py runserver