language: python
services: 
  - postgresql
before_script:
  - psql -c  'create database travic;' -U postgres 
script: 
  - cd msite
  - python manage.py test api
deploy:
  provider: heroku
  api_key: 37e0c908-80ae-4f72-959a-ede65ab7da5a
  app: lexgvapp