# Generated by Django 2.2.5 on 2019-09-03 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190903_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherData',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
